# Camera settings
CAMERA_ID = 0
CAMERA_WIDTH = 0
CAMERA_HEIGHT = 480 
CAMERA_FPS = 30 
FLIP_CAMERA = True

# MediaPipe hand tracking settings 
MAX_HANDS = 1
MIN_DETECTION_CONFIDENCE = 0.7
MIN_TRACKING_CONFIDENCE = 0.7

# Canvas settings
CANVAS_WIDTH = 1280 
CANVAS_HEIGHT = 720 
BRUSH_THICKNESS = 5
ERASER_THICKNESS = 20 
DEFAULT_BRUSH_COLOR = (0, 0, 255)